{dede:noteinfo notename="163" channelid="1" macthtype="string"
refurl="http://" sourcelang="utf-8" cosort="asc" isref="no" exptime="10" usemore="0" /}

{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://novel.hongxiu.com/a/867531/(*).html"
startid="8347335" endid="9922013" addv="1" urlrule="area"
 musthas="" nothas="" listpic="1" usemore="0"}
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div id="htmlContent" class="contentbox" style="color: rgb(0, 0, 0); line-height: 28px;">{/dede:areastart}
    {dede:areaend}</div>{/dede:areaend}
{/dede:listrule}
