<?php
$z[0]=Array("noteinfo","",0,158);
$z[0][4]['notename']="163";
$z[0][4]['channelid']="1";
$z[0][4]['macthtype']="string";
$z[0][4]['refurl']="http://";
$z[0][4]['sourcelang']="utf-8";
$z[0][4]['cosort']="asc";
$z[0][4]['isref']="no";
$z[0][4]['exptime']="10";
$z[0][4]['usemore']="0";
$z[1]=Array("listrule","\r\n    {dede:addurls}http://news.qq.com/a/20120505/index.htm{/dede:addurls}\r\n    {dede:batchrule}{/dede:batchrule}\r\n    {dede:regxrule}{/dede:regxrule}\r\n    {dede:areastart}<iframe width=\"0\" height=\"0\" src=\"/ping.htm\"></iframe>{/dede:areastart}\r\n    {dede:areaend}<object id=\"b5tplugin\" type=\"application/x-bang5taoplugin\" style=\"position:absolute;left:-9000px;top:-9000px;\" width=\"0\" height=\"0\"></object>{/dede:areaend}\r\n",160,805);
$z[1][4]['sourcetype']="hand";
$z[1][4]['rssurl']="http://";
$z[1][4]['regxurl']="http://news.qq.com/a/20120505/index.htm";
$z[1][4]['startid']="20120505";
$z[1][4]['endid']="20150810";
$z[1][4]['addv']="1";
$z[1][4]['urlrule']="area";
$z[1][4]['musthas']="";
$z[1][4]['nothas']="";
$z[1][4]['listpic']="1";
$z[1][4]['usemore']="0";

?>