{dede:noteinfo notename="163" channelid="1" macthtype="string"
    refurl="http://" sourcelang="gb2312" cosort="asc"
  isref="no" exptime="10" usemore="0" /}
{dede:listrule sourcetype="hand" rssurl="http://" regxurl="http://news.qq.com/a/20120505/index.htm"
startid="20120505" endid="20150810" addv="1" urlrule="area" musthas=""
 nothas="" listpic="1" usemore="0"}
    {dede:addurls}http://news.qq.com/a/20120505/index.htm{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<iframe width="0" height="0" src="/ping.htm"></iframe>{/dede:areastart}
    {dede:areaend}<object id="b5tplugin" type="application/x-bang5taoplugin" style="position:absolute;left:-9000px;top:-9000px;" width="0" height="0"></object>{/dede:areaend}
{/dede:listrule}
