
    {dede:addurls}http://news.qq.com/a/20120505/index.htm{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<iframe width="0" height="0" src="/ping.htm"></iframe>{/dede:areastart}
    {dede:areaend}<object id="b5tplugin" type="application/x-bang5taoplugin" style="position:absolute;left:-9000px;top:-9000px;" width="0" height="0"></object>{/dede:areaend}
