<?php
$z[0]=Array("addurls","http://news.qq.com/a/20120505/index.htm",6,74);
$z[1]=Array("batchrule","",80,113);
$z[2]=Array("regxrule","",119,150);
$z[3]=Array("areastart","<iframe width=\"0\" height=\"0\" src=\"/ping.htm\"></iframe>",156,243);
$z[4]=Array("areaend","<object id=\"b5tplugin\" type=\"application/x-bang5taoplugin\" style=\"position:absolute;left:-9000px;top:-9000px;\" width=\"0\" height=\"0\"></object>",249,419);

?>